### ISSUE TITLE
Gratitude

### ISSUE THREAD

**Issue by dengi76** [storm1er/ha_integration_parcelsapp#6]
Thank you so much for your efforts! Everything works great!!!

**Comment by storm1er** [comment]
Thanks haha

It's not done yet ;) 

I'm planning a custom lovelace card that will work a little like template-card:
- Adding the parcel card will ask what card will be used for parcels
- You will be able to match parcel's attribute to selected card parameters
- also a match for a button delete the parcel
- The card will the repeat the selected card for each parcel
- An option to add a form, so you will be able to add a parcel directly from the dashboard

But ... it will be released when it's ready :)

**Comment by dengi76** [comment]
Super! Great idea! You're great!!!
